import { Metadata } from "next";
import "./globals.css";
import '@mantine/core/styles.css';
import { createTheme, MantineProvider } from '@mantine/core';
import Header from "@/component/header";
const theme = createTheme({
  /** Put your mantine theme override here */
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <head>
      </head>
      <body>
      <Header />
      <MantineProvider theme={theme}>
        {children}
      </MantineProvider>
      </body>
      </html>
  );
}
